AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  ScoreBoardEmailGeneratorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ScoreBoardEmailGeneratorFunction
      Handler: com.thelivelock.email_generator.scoreboard.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        ScoreBoardEmailGenerator:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /scoreboard
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ScoreBoardEmailGeneratorApi:
    Description: "API Gateway endpoint URL for Prod stage for ScoreBoardEmailGenerator function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/emailgenerator/ScoreBoard"
  ScoreBoardEmailGeneratorFunction:
    Description: "ScoreBoardEmailGenerator Lambda Function ARN"
    Value: !GetAtt ScoreBoardEmailGeneratorFunction.Arn
  ScoreBoardEmailGeneratorFunctionIamRole:
    Description: "Implicit IAM Role created for Score Box Email Generator function"
    Value: !GetAtt ScoreBoardEmailGeneratorFunctionRole.Arn
